# Generated by Django 4.0.5 on 2022-07-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_alter_reconocimiento_fechahora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reconocimiento',
            old_name='fechaHora',
            new_name='Hora',
        ),
    ]
